# Generated by Django 2.2.5 on 2019-10-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanergy_leave', '0003_auto_20191016_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='Leave_Types',
            field=models.CharField(max_length=40),
        ),
    ]
