# Generated by Django 2.2.5 on 2019-10-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanergy_leave', '0004_auto_20191016_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='leave_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
