# Generated by Django 2.2.5 on 2019-10-18 03:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sanergy_leave', '0005_leavetype_leave_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='applying_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='date of application', null=True),
        ),
    ]
